// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outlet_service/proto/outlet.proto

/*
Package outlet is a generated protocol buffer package.

It is generated from these files:
	outlet_service/proto/outlet.proto

It has these top-level messages:
	Order
	Commodity
	GetRequest
	Response
*/
package outlet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	Id          string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	SumPrice    int32        `protobuf:"varint,3,opt,name=sum_price,json=sumPrice" json:"sum_price,omitempty"`
	UserId      string       `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CourierId   string       `protobuf:"bytes,5,opt,name=courier_id,json=courierId" json:"courier_id,omitempty"`
	Commoditys  []*Commodity `protobuf:"bytes,6,rep,name=commoditys" json:"commoditys,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetSumPrice() int32 {
	if m != nil {
		return m.SumPrice
	}
	return 0
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

func (m *Order) GetCommoditys() []*Commodity {
	if m != nil {
		return m.Commoditys
	}
	return nil
}

type Commodity struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Quantity    int32  `protobuf:"varint,4,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *Commodity) Reset()                    { *m = Commodity{} }
func (m *Commodity) String() string            { return proto.CompactTextString(m) }
func (*Commodity) ProtoMessage()               {}
func (*Commodity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Commodity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Commodity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Commodity) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Commodity) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Response struct {
	Created bool     `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Orders  []*Order `protobuf:"bytes,2,rep,name=orders" json:"orders,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "outlet.Order")
	proto.RegisterType((*Commodity)(nil), "outlet.Commodity")
	proto.RegisterType((*GetRequest)(nil), "outlet.GetRequest")
	proto.RegisterType((*Response)(nil), "outlet.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OutletService service

type OutletServiceClient interface {
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error)
	GetOrders(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type outletServiceClient struct {
	cc *grpc.ClientConn
}

func NewOutletServiceClient(cc *grpc.ClientConn) OutletServiceClient {
	return &outletServiceClient{cc}
}

func (c *outletServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/outlet.OutletService/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outletServiceClient) GetOrders(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/outlet.OutletService/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OutletService service

type OutletServiceServer interface {
	CreateOrder(context.Context, *Order) (*Response, error)
	GetOrders(context.Context, *GetRequest) (*Response, error)
}

func RegisterOutletServiceServer(s *grpc.Server, srv OutletServiceServer) {
	s.RegisterService(&_OutletService_serviceDesc, srv)
}

func _OutletService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutletServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/outlet.OutletService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutletServiceServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutletService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutletServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/outlet.OutletService/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutletServiceServer).GetOrders(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OutletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "outlet.OutletService",
	HandlerType: (*OutletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OutletService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _OutletService_GetOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "outlet_service/proto/outlet.proto",
}

func init() { proto.RegisterFile("outlet_service/proto/outlet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6a, 0xea, 0x40,
	0x14, 0xc6, 0x6f, 0xe2, 0x4d, 0x4c, 0x8e, 0xd7, 0xcb, 0xbd, 0x87, 0x42, 0x07, 0x4b, 0x21, 0x0d,
	0x14, 0x5c, 0x69, 0xab, 0x8f, 0xe0, 0x42, 0xa4, 0x0b, 0xcb, 0xf4, 0x01, 0xc4, 0x66, 0xce, 0x62,
	0xa0, 0x71, 0xe2, 0xfc, 0x11, 0x7c, 0xbc, 0xbe, 0x59, 0xc9, 0x8c, 0xb1, 0x16, 0xba, 0xea, 0xf2,
	0x77, 0x7e, 0x73, 0xc2, 0xf7, 0xcd, 0x04, 0xee, 0x94, 0xb3, 0x6f, 0x64, 0x37, 0x86, 0xf4, 0x41,
	0x56, 0x34, 0x6d, 0xb4, 0xb2, 0x6a, 0x1a, 0x86, 0x13, 0x0f, 0x98, 0x06, 0x2a, 0xdf, 0x23, 0x48,
	0xd6, 0x5a, 0x90, 0xc6, 0xbf, 0x10, 0x4b, 0xc1, 0xa2, 0x22, 0x1a, 0xe7, 0x3c, 0x96, 0x02, 0x0b,
	0x18, 0x08, 0x32, 0x95, 0x96, 0x8d, 0x95, 0x6a, 0xc7, 0x62, 0x2f, 0x2e, 0x47, 0x78, 0x03, 0xb9,
	0x71, 0xf5, 0xa6, 0xd1, 0xb2, 0x22, 0xd6, 0x2b, 0xa2, 0x71, 0xc2, 0x33, 0xe3, 0xea, 0xe7, 0x96,
	0xf1, 0x1a, 0xfa, 0xce, 0x90, 0xde, 0x48, 0xc1, 0x7e, 0xfb, 0xd5, 0xb4, 0xc5, 0x95, 0xc0, 0x5b,
	0x80, 0x4a, 0x39, 0x2d, 0x83, 0x4b, 0xbc, 0xcb, 0x4f, 0x93, 0x95, 0xc0, 0xc7, 0x56, 0xd7, 0xb5,
	0x12, 0xd2, 0x1e, 0x0d, 0x4b, 0x8b, 0xde, 0x78, 0x30, 0xfb, 0x3f, 0x39, 0x65, 0x5f, 0x74, 0x86,
	0x5f, 0x1c, 0x2a, 0x15, 0xe4, 0x67, 0xf1, 0x83, 0x1a, 0x57, 0x90, 0x5c, 0x56, 0x08, 0x80, 0x23,
	0xc8, 0xf6, 0x6e, 0xbb, 0xb3, 0xd2, 0x1e, 0x7d, 0x81, 0x84, 0x9f, 0xb9, 0xfc, 0x03, 0xb0, 0x24,
	0xcb, 0x69, 0xef, 0xc8, 0xd8, 0xf2, 0x09, 0x32, 0x4e, 0xa6, 0x51, 0x3b, 0x43, 0xc8, 0xa0, 0x5f,
	0x69, 0xda, 0x5a, 0x0a, 0x11, 0x32, 0xde, 0x21, 0xde, 0x43, 0xaa, 0xda, 0x7b, 0x36, 0x2c, 0xf6,
	0x9d, 0x86, 0x5d, 0x27, 0x7f, 0xfb, 0xfc, 0x24, 0x67, 0x07, 0x18, 0xae, 0xfd, 0xfc, 0x25, 0xbc,
	0x1d, 0x3e, 0xc0, 0x60, 0xe1, 0x3f, 0x11, 0x5e, 0xe9, 0xeb, 0xda, 0xe8, 0x5f, 0x87, 0x5d, 0x82,
	0xf2, 0x17, 0xce, 0x21, 0x5f, 0x92, 0xf5, 0xde, 0x20, 0x76, 0x07, 0x3e, 0x03, 0x7f, 0xb7, 0xf4,
	0x9a, 0xfa, 0xdf, 0x62, 0xfe, 0x11, 0x00, 0x00, 0xff, 0xff, 0x96, 0xd7, 0x70, 0x6f, 0x3b, 0x02,
	0x00, 0x00,
}
