version: '3.5'

services:
  datastore:
    image: mongo:latest
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    networks:
      - outlet-net
    ports:
      - 27017
    command: mongod --logpath=/dev/null

  database:
    image: postgres
    networks:
      - outlet-net
    ports:
      - 5432

  courier-server:
    restart: always
    container_name: "courier-server"
    build: ./courier_service
    links:
      - datastore
    depends_on:
      - datastore
    networks:
      - outlet-backend-net
      - outlet-net
    environment:
      DB_HOST: "mongodb://datastore:27017"

  outlet-server:
    restart: always
    container_name: "outlet-server"
    build: ./outlet_service
    ports:
      - 50051
    links:
      - datastore
    depends_on:
      - datastore
      - courier-server
    networks:
      - outlet-backend-net
      - outlet-net
    environment:
      DB_HOST: "mongodb://datastore:27017"
      MICRO_ADDRESS: ":50051"

  user-server:
    restart: always
    container_name: "user-server"
    build: ./user_service
    links:
      - database
    depends_on:
      - database
    networks:
      - outlet-backend-net
      - outlet-net
    environment:
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  outlet-client:
    container_name: "outlet-client"
    build: ./outlet_client
    depends_on:
      - outlet-server
    networks:
      - outlet-backend-net

  user-client:
    container_name: "user-client"
    build: ./user_client
    depends_on:
      - user-server
    networks:
      - outlet-backend-net

networks:
  outlet-net:
    name: outlet-net
  outlet-backend-net:
    name: outlet-backend-net
